### ISSUE TITLE
xpresspipe riboseq UMI bug?

### ISSUE THREAD

**Issue by hollyjaro** [XPRESSyourself/XPRESSpipe#38]
Hello,

I am trying to run the xpresspipe riboseq but I am getting the same error, I believe it's from the fastp package for UMI:

TypeError: can only concatenate str (not "int") to str

I tried to play with the --umi_location (read2, "read2", =read2) and --umi_length 5 with I am getting the same error. I am not very skilled in bioinformatics. Please see attached
the log file.
[ribo_pipe.txt](https://github.com/XPRESSyourself/XPRESSpipe/files/4193383/ribo_pipe.txt)

**Comment by j-berg** [comment]
Hi,

I'm so sorry for the delay in getting back to you. For some reason, issues aren't getting sent to my email as I expected. I am working on fixing this so I can be more prompt in responding!

I think I tracked down the bug you mentioned. If you re-install XPRESSpipe using [this version](https://github.com/XPRESSyourself/XPRESSpipe/releases/tag/XPRESSpipe-v0.4.4), it should address the issue you are running into. 

Please don't hesitate to reach out to me if you have more questions!

Jordan

**Comment by j-berg** [comment]
Closing issue. Please re-open if you have any issues with the update or need help. Thanks!
