### ISSUE TITLE
Problem with Running Ribosome Profiling Pipeline

### ISSUE THREAD

**Issue by chenghongdeng** [XPRESSyourself/XPRESSpipe#51]

**Comment by j-berg** [comment]
Hi,

Were you able to figure this question out? I saw you closed the issue, but just wanted to double-check.

**Comment by chenghongdeng** [comment]
Hi Mr or Ms. 

I hope this email finds you well. 

Thanks for asking. Yes, I am able to solve the question. 

Sincerely,
Chenghong Deng

**Comment by j-berg** [comment]
Wonderful! Thanks for the update!
