### ISSUE TITLE
Cannot alignment

### ISSUE THREAD

**Issue by hailong-hu** [XPRESSyourself/XPRESSpipe#54]
**Describe the bug**
I successfully generated the reference according to "xpresspipe curateReference -o /path/to/reference -f /path/to/reference/genome_fastas -g /path/to/reference/transcripts.gtf"

Then I process the dataset according to "xpresspipe riboseq -i /path/to/input -o /path/to/output -r /path/to/reference/ --gtf /path/to/reference//transcripts_CT.gtf -e ribo"

The "triming", "QC" can be completed, but the alignment can not.

Error as shown as: "ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False"

**Desktop (please complete the following information):**
 - On an HPC?
 - Version [e.g. 0.2.3-beta]

**Comment by j-berg** [comment]
Hi,
Sorry for the delay. Could you provide me a sample FASTQ file, along with any log files you receive? You can email them to me at jordanberg.contact@gmail.com

Thanks!
